### ISSUE TITLE
"github.com/Sirupsen/logrus" organization name renamed to lowercase

### ISSUE THREAD

**Issue by smyrman** [desertbit/glue#11]
The sirupsen organization has been renamed to lowercase "github.com/sirupsen/logrus". This causes issues when trying to resolve this project's dependencies.

Imports should be search-replaced to use lower-case "sirupsen"

**Comment by r0l1** [comment]
Merged thanks!

**Comment by CrushedPixel** [comment]
Would you mind adding a new release version? [`go dep`](https://github.com/golang/dep) defaults to the latest tagged release when importing dependencies, and version `1.9.1` does not yet include this fix.
