### ISSUE TITLE
Add MIT dual licence

### ISSUE THREAD

**Issue by conejo** [desertbit/glue#14]
I'd like to use this in a project, but there are several issues related to the GPL that could cause trouble when the js code is distributed in a web app. Would it be possible to add a dual MIT license to this code?

**Comment by BiosElement** [comment]
Shame this hasn't been answered..

**Comment by r0l1** [comment]
I'll change it to MIT as soon as I have some time.

**Comment by gosticks** [comment]
Nice!

**Comment by r0l1** [comment]
@conejo please create a pull request and then I am willing to merge :)

**Comment by ameliabradley** [comment]
@r0l1 Heya. I've made a PR to add a dual license. Let me know if there's anything you'd like to change about it!

Also, thank you for making such a great library.

**Comment by ameliabradley** [comment]
Two possible PRs, depending on what you are going for.

Update to MIT license: https://github.com/desertbit/glue/pull/16

Update to dual GPL and MIT license: https://github.com/desertbit/glue/pull/15

**Comment by r0l1** [comment]
Thanks for the pull request :)
