### ISSUE TITLE
Exposing request to the session

### ISSUE THREAD

**Issue by osiloke** [desertbit/glue#5]
Why
- For token based authentication, and getting the current user from the request
- For access to request params
  ...

**Comment by osiloke** [comment]
It just occurred to me that I can just use the socket id to map the current request user through a middleware.

**Comment by r0l1** [comment]
Could you please explain in detail what is your problem? Some sample code would be great!

I am using glue in my real-time backend library [BitMonster](https://github.com/desertbit/bitmonster) which is  similar to firebase. It supports middleware and is ready to use. I'll add a detailled README as soon as I have some time. You could check it out for middleware usage and authentication.

**Comment by osiloke** [comment]
I'm working on a project which provides an ormish api/server for accessing data stored in any database (sql, nosql, file, memory ...) by using an `automatic schema`. The api can be accessed via regular rest calls, like parse. I want to add a realtime server on top of it.
So i would generate an auth token from the backend and then use that token to authorize a socket session in a middleware through a request query param.
i.e
`
socket.open('http://glue.io/socket?token=jwttoken')
`
`
I don't have any code samples, i'm going through existing projects to see if i need to build my own.
I looked through bitmonster, which is awesome, and it seems to do what i expected but it is tied to rethinkdb but it bitmonster allows me to plug my own auth system, from what i have read.

**Comment by osiloke** [comment]
bitmonster seems to work for my use case with a little tweaking. 
Thanks

**Comment by r0l1** [comment]
Great! How did you tweak it?
You could have a look at the glue utils MarshalValues and UnmarshalValues function. This way, you could attach authentication data to each request. Another possibility would be to create a BitMonster plugin. Similar as the BitMonster auth plugin. To remove the RethinkDB dependency, I could make it optionally.

**Comment by osiloke** [comment]
Yep, thats what i did, drank a lot of coffee, read your code, did a sample and boom!, worked. 
I actually use rethinkdb in my project but i want to be able to switch whenever something new comes up.

**Comment by r0l1** [comment]
Cool! Great I could help you :)
