### ISSUE TITLE
Nix jQuery Dependency

### ISSUE THREAD

**Issue by u382514** [desertbit/glue#7]
This is a great, no nonsense, library. Thanks for creating it! With that said can you possibly entertain the idea of getting rid of the jquery dependency? Jquery is great and all but it's too much fluff when all you need is the ajax portion. At least if continuing to use a dependency maybe change to axios or fetch or something that is specifically created for the job needed. 

Thanks!

**Comment by r0l1** [comment]
Thank you!
That's a good point. I am working on a [new library](https://github.com/desertbit/pakt) which will get a javascript backend similar to glue's functionality. The Ajax backend will be implemente without jQuery. However I would be happy if you are interested to create a pull request for Glue which removes the jQuery dependency.

**Comment by u382514** [comment]
Awesome! Read up on PAKT...that looks very promising too. I've already taken out the the JQuery dependency and replaced it with axios in Glue just to give it a beta test that worked out very well. Shouldn't take too much to take out the dependency even for that. I'll definitely try my hand at a pull request (it'll be my first) and see how that goes.

**Comment by r0l1** [comment]
Thanks. I just finished my work on the [BinarySocket library](https://github.com/desertbit/binarysocket) which will be used by PAKT. I already backported some of the work to Glue to remove the JQuery dependency. However I won't introduce any further big changes to gurantee the stability of this project. Please have a look at 3f81ab68ba24212af9d845b2b97f99f424b4dcc7
