### ISSUE TITLE
Split / Subrepo Javascript Client

### ISSUE THREAD

**Issue by bobbysciacchitano** [desertbit/glue#8]
Hi,

I was wondering if it would be possible to split out the client library so that I can then be published to NPM and other Javascript package management tools and the bought in as a modern dependency?

Thanks.

**Comment by r0l1** [comment]
Hey,

Oh no, npm :scream: !
I prefer bower and always try to avoid using npm. I don't want to make any breaking changes to this repository. This would create more harm than benefit.

I am open to add npm,... support, if that's possible without changing the file structure of this project.

Cheers

**Comment by alecwhittington** [comment]
+1 for npm support. Most projects are moving away from bower, so adding glue to the project becomes a pain without trying to introduce Bower and still wanting to manage the package.
